language: php

php:
  - 7.0
  - 5.5
  - 5.6
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml;
  - vendor/bin/phpcs --extensions=php --standard=PSR2  --ignore=vendor ./;

notifications:
  email: false